name: Gappyfpca CI test

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies (with test extras)
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
      working-directory: .

    - name: Run tests
      run: |
        pytest -v -s
      working-directory: .
